export const countryTimezones = [
  { country: "Afghanistan", timezone: "Asia/Kabul" },
  { country: "Albania", timezone: "Europe/Tirane" },
  { country: "Algeria", timezone: "Africa/Algiers" },
  { country: "Andorra", timezone: "Europe/Andorra" },
  { country: "Angola", timezone: "Africa/Luanda" },
  { country: "Antigua & Barbuda", timezone: "America/Antigua" },
  { country: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { country: "Armenia", timezone: "Asia/Yerevan" },
  { country: "Australia", timezone: "Australia/Sydney" },
  { country: "Austria", timezone: "Europe/Vienna" },
  { country: "Azerbaijan", timezone: "Asia/Baku" },
  { country: "Bahamas", timezone: "America/Nassau" },
  { country: "Bahrain", timezone: "Asia/Bahrain" },
  { country: "Bangladesh", timezone: "Asia/Dhaka" },
  { country: "Barbados", timezone: "America/Barbados" },
  { country: "Belarus", timezone: "Europe/Minsk" },
  { country: "Belgium", timezone: "Europe/Brussels" },
  { country: "Belize", timezone: "America/Belize" },
  { country: "Benin", timezone: "Africa/Porto-Novo" },
  { country: "Bhutan", timezone: "Asia/Thimphu" },
  { country: "Bolivia", timezone: "America/La_Paz" },
  { country: "Bosnia & Herzegovina", timezone: "Europe/Sarajevo" },
  { country: "Botswana", timezone: "Africa/Gaborone" },
  { country: "Brazil", timezone: "America/Sao_Paulo" },
  { country: "Brunei", timezone: "Asia/Brunei" },
  { country: "Bulgaria", timezone: "Europe/Sofia" },
  { country: "Burkina Faso", timezone: "Africa/Ouagadougou" },
  { country: "Burundi", timezone: "Africa/Bujumbura" },
  { country: "Cambodia", timezone: "Asia/Phnom_Penh" },
  { country: "Cameroon", timezone: "Africa/Douala" },
  { country: "Canada", timezone: "America/Toronto" },
  { country: "Chile", timezone: "America/Santiago" },
  { country: "China", timezone: "Asia/Shanghai" },
  { country: "Colombia", timezone: "America/Bogota" },
  { country: "Costa Rica", timezone: "America/Costa_Rica" },
  { country: "Croatia", timezone: "Europe/Zagreb" },
  { country: "Cuba", timezone: "America/Havana" },
  { country: "Cyprus", timezone: "Asia/Nicosia" },
  { country: "Czech Republic", timezone: "Europe/Prague" },
  { country: "Denmark", timezone: "Europe/Copenhagen" },
  { country: "Djibouti", timezone: "Africa/Djibouti" },
  { country: "Dominica", timezone: "America/Dominica" },
  { country: "Dominican Republic", timezone: "America/Santo_Domingo" },
  { country: "East Timor", timezone: "Asia/Dili" },
  { country: "Ecuador", timezone: "America/Guayaquil" },
  { country: "Egypt", timezone: "Africa/Cairo" },
  { country: "El Salvador", timezone: "America/El_Salvador" },
  { country: "Estonia", timezone: "Europe/Tallinn" },
  { country: "Ethiopia", timezone: "Africa/Addis_Ababa" },
  { country: "Fiji", timezone: "Pacific/Fiji" },
  { country: "Finland", timezone: "Europe/Helsinki" },
  { country: "France", timezone: "Europe/Paris" },
  { country: "Germany", timezone: "Europe/Berlin" },
  { country: "Ghana", timezone: "Africa/Accra" },
  { country: "Greece", timezone: "Europe/Athens" },
  { country: "Greenland", timezone: "America/Nuuk" },
  { country: "Guatemala", timezone: "America/Guatemala" },
  { country: "Honduras", timezone: "America/Tegucigalpa" },
  { country: "Hungary", timezone: "Europe/Budapest" },
  { country: "Iceland", timezone: "Atlantic/Reykjavik" },
  { country: "India", timezone: "Asia/Kolkata" },
  { country: "Indonesia", timezone: "Asia/Jakarta" },
  { country: "Iran", timezone: "Asia/Tehran" },
  { country: "Iraq", timezone: "Asia/Baghdad" },
  { country: "Ireland", timezone: "Europe/Dublin" },
  { country: "Israel", timezone: "Asia/Jerusalem" },
  { country: "Italy", timezone: "Europe/Rome" },
  { country: "Jamaica", timezone: "America/Jamaica" },
  { country: "Japan", timezone: "Asia/Tokyo" },
  { country: "Jordan", timezone: "Asia/Amman" },
  { country: "Kazakhstan", timezone: "Asia/Almaty" },
  { country: "Kenya", timezone: "Africa/Nairobi" },
  { country: "Kuwait", timezone: "Asia/Kuwait" },
  { country: "Laos", timezone: "Asia/Vientiane" },
  { country: "Latvia", timezone: "Europe/Riga" },
  { country: "Lebanon", timezone: "Asia/Beirut" },
  { country: "Lithuania", timezone: "Europe/Vilnius" },
  { country: "Luxembourg", timezone: "Europe/Luxembourg" },
  { country: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { country: "Maldives", timezone: "Indian/Maldives" },
  { country: "Malta", timezone: "Europe/Malta" },
  { country: "Mexico", timezone: "America/Mexico_City" },
  { country: "Mongolia", timezone: "Asia/Ulaanbaatar" },
  { country: "Morocco", timezone: "Africa/Casablanca" },
  { country: "Myanmar", timezone: "Asia/Yangon" },
  { country: "Nepal", timezone: "Asia/Kathmandu" },
  { country: "Netherlands", timezone: "Europe/Amsterdam" },
  { country: "New Zealand", timezone: "Pacific/Auckland" },
  { country: "Nigeria", timezone: "Africa/Lagos" },
  { country: "Norway", timezone: "Europe/Oslo" },
  { country: "Pakistan", timezone: "Asia/Karachi" },
  { country: "Philippines", timezone: "Asia/Manila" },
  { country: "Poland", timezone: "Europe/Warsaw" },
  { country: "Portugal", timezone: "Europe/Lisbon" },
  { country: "Qatar", timezone: "Asia/Qatar" },
  { country: "Romania", timezone: "Europe/Bucharest" },
  { country: "Russia", timezone: "Europe/Moscow" },
  { country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { country: "Singapore", timezone: "Asia/Singapore" },
  { country: "Slovakia", timezone: "Europe/Bratislava" },
  { country: "Slovenia", timezone: "Europe/Ljubljana" },
  { country: "South Africa", timezone: "Africa/Johannesburg" },
  { country: "South Korea", timezone: "Asia/Seoul" },
  { country: "Spain", timezone: "Europe/Madrid" },
  { country: "Sri Lanka", timezone: "Asia/Colombo" },
  { country: "Sweden", timezone: "Europe/Stockholm" },
  { country: "Switzerland", timezone: "Europe/Zurich" },
  { country: "Thailand", timezone: "Asia/Bangkok" },
  { country: "Turkey", timezone: "Europe/Istanbul" },
  { country: "Uganda", timezone: "Africa/Kampala" },
  { country: "Ukraine", timezone: "Europe/Kiev" },
  { country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { country: "United Kingdom", timezone: "Europe/London" },
  { country: "United States", timezone: "America/New_York" },
  { country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { country: "Zimbabwe", timezone: "Africa/Harare" }
];
